# Generated by Django 3.2.1 on 2021-05-28 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20210529_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time_visit',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_visit',
            field=models.CharField(max_length=200),
        ),
    ]
