# Generated by Django 3.2.1 on 2021-05-29 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20210529_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
