# Generated by Django 3.2.1 on 2021-05-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_visit_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date_visit',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='time_visit',
        ),
    ]
