# Generated by Django 3.2.1 on 2021-05-29 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0007_auto_20210529_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='name',
        ),
        migrations.AddField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
